services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    env_file: 
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - alfa-net  # Adicionando o MySQL à rede alfa-net

  python_app:
    build: .
    container_name: python_app
    depends_on:
      - mysql
    volumes:
      - .:/app
    env_file: 
      - .env
    stdin_open: true
    tty: true
    networks:
      - alfa-net

volumes:
  mysql_data:

networks:
  alfa-net: 
    driver: bridge
